version: "3.3"
services:

  backend:
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: /start-reload.sh
