version: "3.3"
services:

  db:
    image: postgres:13.2
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}

  backend:
    image: 'backend.dockerfile:latest'
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile

volumes:
  app-db-data: