"""Init base tables

Revision ID: 01
Revises: 
Create Date: 2021-03-31 18:16:23.216600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("wallet_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("amount", sa.Numeric(scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_wallet_wallet_id"), "wallet", ["wallet_id"], unique=True)
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("amount", sa.Numeric(scale=2), nullable=True),
        sa.Column("from_wallet_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("from_wallet_amount", sa.Numeric(scale=2), nullable=True),
        sa.Column("to_wallet_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("to_wallet_amount", sa.Numeric(scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_wallet_id"],
            ["wallet.wallet_id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_wallet_id"],
            ["wallet.wallet_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_transaction_from_wallet_id"),
        "transaction",
        ["from_wallet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_to_wallet_id"),
        "transaction",
        ["to_wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_to_wallet_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_from_wallet_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_wallet_wallet_id"), table_name="wallet")
    op.drop_table("wallet")
    # ### end Alembic commands ###
